### ISSUE TITLE
once: 2016-11-26 23:59:56 ParkingChecklistFilled ERROR

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#155]
```
Exception while running check. Traceback: Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context context) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute cursor.execute(statement, parameters) File "/opt/conda/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute result = self._query(query) File "/opt/conda/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 835, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 1019, in _read_query_result result.read() File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 1302, in read first_packet = self.connection._read_packet() File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 961, in _read_packet packet_header = self._read_bytes(4) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 998, in _read_bytes 2013, "Lost connection to MySQL server during query") pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query') The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/custos/checks/__init__.py", line 83, in wrapped_check self.check(*args, **kwargs) File "/opt/conda/lib/python3.5/site-packages/shifthelper/checks.py", line 41, in check if all([f() for f in self.checklist]): File "/opt/conda/lib/python3.5/site-packages/shifthelper/checks.py", line 41, in <listcomp> if all([f() for f in self.checklist]): File "/opt/conda/lib/python3.5/site-packages/wrapt/wrappers.py", line 522, in __call__ args, kwargs) File "/opt/conda/lib/python3.5/site-packages/shifthelper/debug_log_wrapper.py", line 9, in log_call_and_result result = wrapped(*args, **kwargs) File "/opt/conda/lib/python3.5/site-packages/shifthelper/conditions.py", line 289, in is_checklist_not_filled return get_last_parking_checklist_entry() < get_last_shutdown() File "/opt/conda/lib/python3.5/site-packages/shifthelper/tools/__init__.py", line 52, in get_last_parking_checklist_entry create_db_connection(config['sandbox_db']) File "/opt/conda/lib/python3.5/site-packages/pandas/io/sql.py", line 331, in read_sql_query parse_dates=parse_dates, chunksize=chunksize) File "/opt/conda/lib/python3.5/site-packages/pandas/io/sql.py", line 1084, in read_query result = self.execute(*args) File "/opt/conda/lib/python3.5/site-packages/pandas/io/sql.py", line 975, in execute return self.connectable.execute(*args, **kwargs) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2058, in execute return connection.execute(statement, *multiparams, **params) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 939, in execute return self._execute_text(object, multiparams, params) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text statement, parameters File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context context) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception exc_info File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise raise value.with_traceback(tb) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context context) File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute cursor.execute(statement, parameters) File "/opt/conda/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute result = self._query(query) File "/opt/conda/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 835, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 1019, in _read_query_result result.read() File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 1302, in read first_packet = self.connection._read_packet() File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 961, in _read_packet packet_header = self._read_bytes(4) File "/opt/conda/lib/python3.5/site-packages/pymysql/connections.py", line 998, in _read_bytes 2013, "Lost connection to MySQL server during query") sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: 'select * from park_checklist_filled'] 
```

**Comment by dneise** [comment]
duplicate of #156
