### ISSUE TITLE
once: 2016-11-27 04:43:20 BiasNotOperatingDuringDataRun ERROR

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper#157]
```
2016-11-27 04:43:24,861 - custos.notify.log - ERROR - Check: BiasNotOperatingDuringDataRun - Message: Exception while running check. Traceback:
 Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/custos/checks/__init__.py", line 83, in wrapped_check
    self.check(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/shifthelper/checks.py", line 41, in check 
    if all([f() for f in self.checklist]):
  File "/opt/conda/lib/python3.5/site-packages/shifthelper/checks.py", line 41, in <listcomp>
    if all([f() for f in self.checklist]):
  File "/opt/conda/lib/python3.5/site-packages/wrapt/wrappers.py", line 522, in __call__
    args, kwargs)
  File "/opt/conda/lib/python3.5/site-packages/shifthelper/debug_log_wrapper.py", line 9, in log_call_and_result
    result = wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/shifthelper/conditions.py", line 95, in is_data_run
    sfc.main_page().system_status
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by dneise** [comment]
This error comes from this part: 
https://github.com/fact-project/shifthelper/blob/run_all_day_long/shifthelper/conditions.py#L93
```{python}
        config_name = regex.search(
            r'\[(.*)\]',
            sfc.main_page().system_status
            ).groups()[0]
```
So we should check for `None` being the result of `regex.search`, but what is the reation? 
I would say. If we can't find out the `config_name`, we assume it's not a data run, ok?

**Comment by dneise** [comment]
It's probably just for a moment.
